# Generated by Django 3.0 on 2019-12-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='Username')),
                ('user_phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('user_email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
